image : gcc:latest

stages:
  - build

build:
  before_script:
  - echo "deb http://ftp.fr.debian.org/debian testing main" >> /etc/apt/sources.list
  - apt-get update --yes
  - apt-get install --yes cmake xvfb libluajit-5.1-dev libphysfs-dev libopenal-dev libmodplug-dev libvorbis-dev qtbase5-dev qttools5-dev qttools5-dev-tools libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev
  stage: build
  script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make -j4  && xvfb-run -a --server-args "-screen 0 1920x1080x24" -e /dev/stderr ctest -V
